<?php

use Illuminate\Database\Seeder;

class ServiceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    protected $services = array(
        array('category_id' => '151','name' => 'маникюр','price' => '10.00','time' => '30'),
        array('category_id' => '151','name' => 'маникюр с гел лак BLUESKY','price' => '20.00','time' => '60'),
        array('category_id' => '151','name' => 'маникюр с лак OPI','price' => '12.00','time' => '50'),
        array('category_id' => '151','name' => 'френски маникюр с гел лак BLUESKY','price' => '24.00','time' => '60'),
        array('category_id' => '151','name' => 'френски маникюр с лак OPI','price' => '12.00','time' => '60'),
        array('category_id' => '152','name' => 'рисунка','price' => '1.00','time' => '30'),
        array('category_id' => '152','name' => 'декорация с камъчета','price' => '1.00','time' => '30'),
        array('category_id' => '152','name' => 'декорация с печат','price' => '0.50','time' => '30'),
        array('category_id' => '153','name' => 'сваляне на гел лак','price' => '5.00','time' => '25'),
        array('category_id' => '153','name' => 'лакиране с гел лак BLUESKY','price' => '12.00','time' => '30'),
        array('category_id' => '153','name' => 'сваляне на лак','price' => '3.00','time' => '10'),
        array('category_id' => '153','name' => 'лакиране с OPI','price' => '5.00','time' => '20'),
        array('category_id' => '154','name' => 'лепене на нокът','price' => '2.00','time' => '60'),
        array('category_id' => '154','name' => 'изграждане с изграждащ гел','price' => '40.00','time' => '120'),
        array('category_id' => '154','name' => 'поддръжка с изграждащ гел','price' => '25.00','time' => '60'),
        array('category_id' => '154','name' => 'сваляне на изграждащ гел','price' => '15.00','time' => '45'),
        array('category_id' => '155','name' => 'пeдикюр','price' => '20.00','time' => '60'),
        array('category_id' => '155','name' => 'пeдикюр с гел лак BLUESKY','price' => '30.00','time' => '60'),
        array('category_id' => '155','name' => 'педикюр с лак OPI','price' => '25.00','time' => '60'),
        array('category_id' => '155','name' => 'СПА педикюр','price' => '35.00','time' => '90'),
        array('category_id' => '156','name' => 'оформяне на вежди','price' => '7.00','time' => '20'),
        array('category_id' => '156','name' => 'боядисване на вежди','price' => '7.00','time' => '2'),
        array('category_id' => '156','name' => 'почистванена лице','price' => '25.00','time' => '60'),
        array('category_id' => '156','name' => 'масаж на лице 20 мин.','price' => '20.00','time' => '20'),
        array('category_id' => '157','name' => 'терапия anti-age','price' => '40.00','time' => '90'),
        array('category_id' => '157','name' => 'терапия стоп акне','price' => '40.00','time' => '90'),
        array('category_id' => '157','name' => 'терапия за суха кожа','price' => '40.00','time' => '90'),
        array('category_id' => '157','name' => 'терапия за деликатна кожа','price' => '40.00','time' => '90'),
        array('category_id' => '160','name' => 'горна устна','price' => '5.00','time' => '20'),
        array('category_id' => '160','name' => 'ръце','price' => '15.00','time' => '30'),
        array('category_id' => '160','name' => 'подмишници','price' => '7.00','time' => '20'),
        array('category_id' => '160','name' => 'врат','price' => '10.00','time' => '20'),
        array('category_id' => '161','name' => 'гърди','price' => '10.00','time' => '30'),
        array('category_id' => '160','name' => 'гръб','price' => '20.00','time' => '50'),
        array('category_id' => '161','name' => 'корем','price' => '10.00','time' => '30'),
        array('category_id' => '161','name' => 'половин крака','price' => '15.00','time' => '40'),
        array('category_id' => '161','name' => 'цели крака','price' => '35.00','time' => '60'),
        array('category_id' => '161','name' => 'триъгълник','price' => '15.00','time' => '30'),
        array('category_id' => '146','name' => 'лице 20 мин','price' => '20.00','time' => '20'),
        array('category_id' => '146','name' => 'врат,лицеи глава 30 мин','price' => '30.00','time' => '30'),
        array('category_id' => '146','name' => 'гръб,врат и лице 30 мин','price' => '30.00','time' => '30'),
        array('category_id' => '146','name' => 'крака 20 мин','price' => '20.00','time' => '20'),
        array('category_id' => '163','name' => 'класически цяло тяло 45 мин','price' => '45.00','time' => '45'),
        array('category_id' => '163','name' => 'спортен цяло тяло 60 мин','price' => '60.00','time' => '60'),
        array('category_id' => '163','name' => 'релаксиращ цяло тяло 45 мин','price' => '40.00','time' => '45'),
        array('category_id' => '163','name' => 'китайски цяло тяло 45 мин','price' => '45.00','time' => '45'),
        array('category_id' => '164','name' => 'рефлексотерапия 20 мин','price' => '20.00','time' => '20'),
        array('category_id' => '164','name' => 'ароматотерапия','price' => '30.00','time' => '60'),
        array('category_id' => '165','name' => 'мъжко подстригване','price' => '10.00','time' => '30'),
        array('category_id' => '165','name' => 'дамско къса коса','price' => '12.00','time' => '40'),
        array('category_id' => '165','name' => 'дамско средна коса','price' => '14.00','time' => '40'),
        array('category_id' => '165','name' => 'дамско дълга коса','price' => '15.00','time' => '40'),
        array('category_id' => '165','name' => 'почистване на цъвтеж кичур по кичур','price' => '20.00','time' => '60'),
        array('category_id' => '166','name' => 'къса коса','price' => '12.00','time' => '40'),
        array('category_id' => '166','name' => 'средна коса','price' => '15.00','time' => '50'),
        array('category_id' => '166','name' => 'дълга коса','price' => '18.00','time' => '60'),
        array('category_id' => '166','name' => 'много дълга коса','price' => '25.00','time' => '60'),
        array('category_id' => '167','name' => 'мъжко','price' => '15.00','time' => '40'),
        array('category_id' => '167','name' => 'дамско къса коса','price' => '15.00','time' => '40'),
        array('category_id' => '167','name' => 'дамско средна коса','price' => '23.00','time' => '60'),
        array('category_id' => '167','name' => 'дамско дълга коса','price' => '25.00','time' => '60'),
        array('category_id' => '168','name' => 'къса коса','price' => '20.00','time' => '60'),
        array('category_id' => '168','name' => 'средна коса','price' => '30.00','time' => '60'),
        array('category_id' => '168','name' => 'дълга коса','price' => '40.00','time' => '60'),
        array('category_id' => '168','name' => 'много дълга коса','price' => '50.00','time' => '60'),
        array('category_id' => '169','name' => 'къса коса','price' => '40.00','time' => '90'),
        array('category_id' => '169','name' => 'средна коса','price' => '60.00','time' => '120'),
        array('category_id' => '169','name' => 'дълга коса','price' => '80.00','time' => '120'),
        array('category_id' => '169','name' => 'много дълга коса','price' => '100.00','time' => '150'),
        array('category_id' => '170','name' => 'къса коса','price' => '10.00','time' => '30'),
        array('category_id' => '170','name' => 'средна коса','price' => '15.00','time' => '40'),
        array('category_id' => '170','name' => 'дълга коса','price' => '25.00','time' => '60'),
        array('category_id' => '170','name' => 'много дълга коса','price' => '30.00','time' => '60'),
        array('category_id' => '171','name' => 'къса коса','price' => '10.00','time' => '30'),
        array('category_id' => '171','name' => 'средна коса','price' => '15.00','time' => '40'),
        array('category_id' => '171','name' => 'дълга коса','price' => '20.00','time' => '60'),
        array('category_id' => '171','name' => 'много дълга коса','price' => '30.00','time' => '60'),
        array('category_id' => '172','name' => 'къса коса','price' => '25.00','time' => '60'),
        array('category_id' => '172','name' => 'средна коса','price' => '30.00','time' => '90'),
        array('category_id' => '172','name' => 'дълга коса','price' => '40.00','time' => '90'),
        array('category_id' => '172','name' => 'много дълга коса','price' => '50.00','time' => '120'),
        array('category_id' => '173','name' => 'къса коса','price' => '25.00','time' => '60'),
        array('category_id' => '173','name' => 'средна коса','price' => '30.00','time' => '90'),
        array('category_id' => '173','name' => 'дълга коса','price' => '40.00','time' => '90'),
        array('category_id' => '173','name' => 'много дълга коса','price' => '50.00','time' => '120'),
        array('category_id' => '174','name' => 'къса коса','price' => '20.00','time' => '60'),
        array('category_id' => '174','name' => 'средна коса','price' => '25.00','time' => '90'),
        array('category_id' => '174','name' => 'дълга коса','price' => '30.00','time' => '90'),
        array('category_id' => '174','name' => 'много дълга коса','price' => '40.00','time' => '120'),
        array('category_id' => '175','name' => 'къса коса','price' => '22.00','time' => '60'),
        array('category_id' => '175','name' => 'средна коса','price' => '27.00','time' => '90'),
        array('category_id' => '175','name' => 'дълга коса','price' => '35.00','time' => '90'),
        array('category_id' => '175','name' => 'много дълга коса','price' => '40.00','time' => '120'),
        array('category_id' => '176','name' => 'боядисване с UOMO','price' => '15.00','time' => '30'),
        array('category_id' => '176','name' => 'подстригване,боядисване с UOMO','price' => '25.00','time' => '50'),
        array('category_id' => '176','name' => 'боядисване с VIOLA','price' => '18.00','time' => '30'),
        array('category_id' => '176','name' => 'подстригване,боядисване с VOILA','price' => '28.00','time' => '50'),
        array('category_id' => '177','name' => 'къса коса','price' => '20.00','time' => '60'),
        array('category_id' => '177','name' => 'средна коса','price' => '25.00','time' => '90'),
        array('category_id' => '177','name' => 'дълга коса','price' => '35.00','time' => '90'),
        array('category_id' => '177','name' => 'много дълга коса','price' => '45.00','time' => '120'),
        array('category_id' => '178','name' => 'къса коса','price' => '25.00','time' => '60'),
        array('category_id' => '178','name' => 'средна коса','price' => '30.00','time' => '90'),
        array('category_id' => '178','name' => 'дълга коса','price' => '40.00','time' => '90'),
        array('category_id' => '178','name' => 'много дълга коса','price' => '50.00','time' => '120'),
        array('category_id' => '179','name' => 'къса коса','price' => '30.00','time' => '120'),
        array('category_id' => '179','name' => 'средна коса','price' => '40.00','time' => '150'),
        array('category_id' => '179','name' => 'дълга коса','price' => '60.00','time' => '180'),
        array('category_id' => '179','name' => 'много дълга коса','price' => '70.00','time' => '180'),
        array('category_id' => '180','name' => 'къса коса','price' => '22.00','time' => '60'),
        array('category_id' => '180','name' => 'средна коса','price' => '28.00','time' => '90'),
        array('category_id' => '180','name' => 'дълга коса','price' => '35.00','time' => '90'),
        array('category_id' => '180','name' => 'много дълга коса','price' => '40.00','time' => '120'),
        array('category_id' => '146','name' => 'антицелулитен масаж ','price' => '20.00','time' => '60'),
        array('category_id' => '182','name' => 'Грим','price' => '1.00','time' => '60'),
        array('category_id' => '183','name' => 'масаж + гимнастика 30 мин','price' => '30.00','time' => '60'),
        array('category_id' => '183','name' => 'масаж + гимнастика 50 мин ','price' => '40.00','time' => '50'),
        array('category_id' => '183','name' => 'масаж + гимнастика 60 мин ','price' => '50.00','time' => '30')
    );
    public function run()
    {
        foreach($this->services as $service){
            \App\Service::create($service);
        }
    }
}
